################################
#  여기는 prod(배포)용입니다.     #
################################

spring:
  application:
    name: 404Jerry

  data:
    redis:
      host: localhost
      port: 6379

  # OAuth2
  security:
    oauth2:
      #TODO 필요한 것들 추가하기
      client:

  # JPA & Hibernate 설정
  jpa:
    hibernate:
      # 운영 환경에서는 절대 'create'나 'update'를 사용하지 않습니다.
      ddl-auto: validate
    properties:
      hibernate:
        # MySQL 9.x 호환
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
          batch_versioned_data: true
          batch_size: 30
        order_inserts: true
        order_updates: true
    # OSIV 비활성화 (백엔드 API 추천)
    open-in-view: false

  # MYSQL_DataSource 설정 (MySQL 9.5.0)
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 스프링 서버 설정
  server:
    port: 8080 # 젠킨스는 8081
    servlet:
      context-path:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

  logging:
    level:
      root: info
      # 운영 서버는 로그를 최소화하여 성능 유지
      org.hibernate.SQL: warn