################################
#  여기는 prod(배포)용입니다.     #
################################

spring:
  application:
    name: 404Jerry

  # 1. 데이터베이스 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA & Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false # 운영 환경에서는 성능을 위해 false 권장
        show_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  # 3. Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  # 4. OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID_GOOGLE}
            client-secret: ${CLIENT_SECRET_GOOGLE}
            scope: email, profile
            redirect-uri: ${REDIRECT_URI_GOOGLE}
            client-name: Google
            authorization-grant-type: authorization_code
          naver:
            client-id: ${CLIENT_ID_NAVER}
            client-secret: ${CLIENT_SECRET_NAVER}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI_NAVER}
            scope: name, email
            client-name: Naver
          kakao:
            client-id: ${CLIENT_ID_KAKAO}
            client-secret: ${CLIENT_SECRET_KAKAO}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI_KAKAO}
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# --------------------------------------------------
# 외부 라이브러리 및 독자 설정 (spring 계층 밖)
# --------------------------------------------------

# JWT 설정
jwt:
  accsecret: ${JWT_ACCSECRET}
  refsecret: ${JWT_REFSECRET}
  access-token-expiration: 1800000      # 30분
  refresh-token-expiration: 604800000   # 7일

# 서버 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    root: info
    org.hibernate.SQL: warn

# Kakao API 전용 (독자 설정)
kakao:
  api:
    key: ${KAKAO_API_KEY}

# 공공데이터 (독자 설정)
public-data:
  api:
    url: ${PUBLIC_DATA_URL}
    key: ${PUBLIC_DATA_KEY}